## Лабораторна робота №1 з глибинного навчання студента групи Ім-17 Волошина Дениса

In [1]:
import numpy as np
from numpy.linalg import norm

In [2]:
def distance_print(distance_mat, eq_num):
    
    val = distance_mat[~np.eye(distance_mat.shape[0],dtype=bool)].min()
    bool_arr = distance_mat == val
    idx = []
    for i in range(bool_arr.shape[0]):
        for j in range(bool_arr.shape[1]):
            if i == j:
                continue
            else:
                if bool_arr[i][j] == True:
                    idx.append([i, j])
    print(f"Для формули {eq_num} відстані: \n")
    print(distance_mat) 
    print('\n' + "Найменшим елементом є " + str(val) + '\n')
    print('Йому відповідають шаблони: ', end=' ')
    for val in idx:
        print(str(val[0]+1) + " та " + str(val[1]+1), end='; ')
    print('\n')

# 2.1 Індивідуальні завдання першого блоку

## 3.1

In [3]:
def L_2(s, x):
    return np.sqrt(np.sum((s-x)**2))

def L_3(s, x, lambd):
    return (np.sum((s-x)**(lambd)))**(1/lambd)

def L_4(s, x):
    return np.sum(np.abs(s-x))

def L_5(s, x, eta):
    return np.sqrt(eta @ ((s-x)**2).T)

def L_6(s, x, lambd, eta):
    return (eta @ ((s-x)**lambd).T)**(1/lambd)

def L_7(s, x, eta):
    return eta @ (np.abs(s-x)).T

def L_8(s, x):
    return np.sum(np.abs(s-x)/np.abs(s+x))

def L_9(s, x):
    n = x.shape[0]
    summa = 0
    for q in range(0, n-1):
        for k in range(1, n):
            if k>q:
                summa += np.sign(s[q]-s[k]) * np.sign(x[q]-x[k])
    return 1 - (2/(n*(n-1))) * summa

def L_10(s, x):
    return np.max(np.abs(s-x))

## 3.2

### Зчитати з файлу

In [13]:
name_of_matrix = "first_block_X.txt"
name_of_weights = "first_block_weights.txt"

X = np.loadtxt(name_of_matrix, delimiter=',')
eta_of_weights = np.loadtxt(name_of_weights, delimiter=',')
n = X.shape[0]
m = X.shape[1]

### Згенерувати випадковим чином

In [4]:
n = 5
m = 6
X = np.random.sample((n,m))
eta = np.random.sample(m)

### Ініціалізуємо матриці відстаней та виводимо зчитані дані

In [14]:
lamd = 4
L_2_distances = np.zeros((n,n))
L_3_distances = np.zeros((n,n))
L_4_distances = np.zeros((n,n))
L_5_distances = np.zeros((n,n))
L_6_distances = np.zeros((n,n))
L_7_distances = np.zeros((n,n))
L_8_distances = np.zeros((n,n))
L_9_distances = np.zeros((n,n))
L_10_distances = np.zeros((n,n))

print("Матриця шаблонів :")
print("\n")
print(X)
print("\n")
print("Матриця вагових коефіцієнтів: ")
print("\n")
print(eta)

Матриця шаблонів :





[[0.82141972 0.04642155 0.64588296 0.59955833 0.54348868 0.41846437]

 [0.88574574 0.31988043 0.6388927  0.17943034 0.88372288 0.01598445]

 [0.3462443  0.7624472  0.31300019 0.96322643 0.79033617 0.12397609]

 [0.7063229  0.5163329  0.65039904 0.33653938 0.98784613 0.326713  ]

 [0.95537726 0.73712664 0.22150833 0.0243943  0.05667627 0.6166563 ]]





Матриця вагових коефіцієнтів: 





[0.97881025 0.33173321 0.91515194 0.92442063 0.45940727 0.92583844]


In [ ]:
for i in range(n):
    for j in range(n):
        L_2_distances[i][j] = L_2(X[i], X[j]) 
        L_3_distances[i][j] = L_3(X[i], X[j], lambd=lamd)
        L_4_distances[i][j] = L_4(X[i], X[j])
        L_5_distances[i][j] = L_5(X[i], X[j], eta=eta)
        L_6_distances[i][j] = L_6(X[i], X[j], lambd=lamd, eta=eta)
        L_7_distances[i][j] = L_7(X[i], X[j], eta=eta)
        L_8_distances[i][j] = L_8(X[i], X[j])
        L_9_distances[i][j] = L_9(X[i], X[j])
        L_10_distances[i][j] = L_10(X[i], X[j])

In [ ]:
distance_print(L_2_distances, 2)
distance_print(L_3_distances, 3)
distance_print(L_4_distances, 4)
distance_print(L_5_distances, 5)
distance_print(L_6_distances, 6)
distance_print(L_7_distances, 7)
distance_print(L_8_distances, 8)
distance_print(L_9_distances, 9)
distance_print(L_10_distances, 10)

# 2.2 Індивідуальні завдання другого блоку

## 3.1

In [21]:
def _a(patt_i, patt_j):
    return patt_j @ patt_i.T

def _b(patt_i, patt_j):
    return (1-patt_j) @ (1-patt_i).T

def _g(patt_i, patt_j):
    return patt_i @ (1-patt_j).T

def _h(patt_i, patt_j):
    return (1-patt_i) @ patt_j.T

def S_1(X_i, X_j):
    a = _a(X_i, X_j)
    b = _b(X_i, X_j)
    g = _g(X_i, X_j)
    h = _h(X_i, X_j)
    n = a + b + g + h

    return a/n

def S_2(X_i, X_j):
    a = _a(X_i, X_j)
    b = _b(X_i, X_j)
    g = _g(X_i, X_j)
    h = _h(X_i, X_j)
    
    return a/(a+g+h)

def S_3(X_i, X_j):
    a = _a(X_i, X_j)
    g = _g(X_i, X_j)
    h = _h(X_i, X_j)
    
    return a/(2*a+g+h)

def S_4(X_i, X_j):
    a = _a(X_i, X_j)
    g = _g(X_i, X_j)
    h = _h(X_i, X_j)
    
    return a/(a+2*(g+h))

def S_5(X_i, X_j):
    a = _a(X_i, X_j)
    b = _b(X_i, X_j)
    g = _g(X_i, X_j)
    h = _h(X_i, X_j)
    n = a + b + g + h
    
    return (a+b)/n

def S_6(X_i, X_j):
    a = _a(X_i, X_j)
    g = _g(X_i, X_j)
    h = _h(X_i, X_j)
    
    return a/(g+h)

def S_7(X_i, X_j):
    a = _a(X_i, X_j)
    b = _b(X_i, X_j)
    g = _g(X_i, X_j)
    h = _h(X_i, X_j)
    
    return (a*b-g*h)/(a*b+g*h)

def mean_euclid(X_i, X_j): # завдання 3.3 індивідуального блоку. Протестуємо серендню Евклідову відстань  
    a = _a(X_i, X_j)
    b = _b(X_i, X_j)
    g = _g(X_i, X_j)
    h = _h(X_i, X_j)
    n = a + b + g + h
    
    return np.sqrt((g+h)/n)

def hamming(X_i, X_j): # завдання 3.5 індивідуального блоку. Протестуємо відстань Хеммінга
    g = _g(X_i, X_j)
    h = _h(X_i, X_j)
    
    return g+h


## 3.2

### Зчитування з файлів

In [36]:
name_of_matrix_2 = "second_block_X_2.txt"

X_2 = np.loadtxt(name_of_matrix_2, delimiter=',', dtype=None)

n = X_2.shape[0]
m = X_2.shape[1]

### Генерація випадковим чином

In [33]:
n = 5
m = 4
X_2 = np.random.binomial(1, 0.5, size=(n,m))

### Ініціалізуємо матрицю відстаней та виводимо дані

In [37]:
S_1_distances = np.zeros((n,n))
S_2_distances = np.zeros((n,n))
S_3_distances = np.zeros((n,n))
S_4_distances = np.zeros((n,n))
S_5_distances = np.zeros((n,n))
S_6_distances = np.zeros((n,n))
S_7_distances = np.zeros((n,n))
mean_euclid_distances = np.zeros((n,n)) # завдання 3.3
hamming_distances = np.zeros((n,n)) # завдання 3.5

print("Матриця шаблонів: ")
print("\n")
print(X_2)

Матриця шаблонів: 





[[1. 0. 1. 1.]

 [0. 1. 1. 1.]

 [0. 1. 0. 1.]

 [1. 0. 0. 1.]

 [0. 1. 0. 0.]]


In [38]:
for i in range(n):
    for j in range(n):
        S_1_distances[i][j] = S_1(X_2[i], X_2[j]) 
        S_2_distances[i][j] = S_2(X_2[i], X_2[j])
        S_3_distances[i][j] = S_3(X_2[i], X_2[j])
        S_4_distances[i][j] = S_4(X_2[i], X_2[j])
        S_5_distances[i][j] = S_5(X_2[i], X_2[j])
        S_6_distances[i][j] = S_6(X_2[i], X_2[j])
        S_7_distances[i][j] = S_7(X_2[i], X_2[j])

C:\Users\Andrii\AppData\Local\Temp\ipykernel_5292\787013973.py:58: RuntimeWarning: divide by zero encountered in double_scalars

  return a/(g+h)


In [39]:
distance_print(S_1_distances, 1)
distance_print(S_2_distances, 2)
distance_print(S_3_distances, 3)
distance_print(S_4_distances, 4)
distance_print(S_5_distances, 5)
distance_print(S_6_distances, 6)
distance_print(S_7_distances, 7)

Для формули 1 відстані: 



[[0.75 0.5  0.25 0.5  0.  ]

 [0.5  0.75 0.5  0.25 0.25]

 [0.25 0.5  0.5  0.25 0.25]

 [0.5  0.25 0.25 0.5  0.  ]

 [0.   0.25 0.25 0.   0.25]]



Найменшим елементом є 0.0



Йому відповідають шаблони:  1 та 5; 4 та 5; 5 та 1; 5 та 4; 



Для формули 2 відстані: 



[[1.         0.5        0.25       0.66666667 0.        ]

 [0.5        1.         0.66666667 0.25       0.33333333]

 [0.25       0.66666667 1.         0.33333333 0.5       ]

 [0.66666667 0.25       0.33333333 1.         0.        ]

 [0.         0.33333333 0.5        0.         1.        ]]



Найменшим елементом є 0.0



Йому відповідають шаблони:  1 та 5; 4 та 5; 5 та 1; 5 та 4; 



Для формули 3 відстані: 



[[0.5        0.33333333 0.2        0.4        0.        ]

 [0.33333333 0.5        0.4        0.2        0.25      ]

 [0.2        0.4        0.5        0.25       0.33333333]

 [0.4        0.2        0.25       0.5        0.        ]

 [0.         0.25       0.33333333 0.         0.